name: dart_api
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  alfred:
  dart_jsonwebtoken:
  postgres:
  socket_io_client:  
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
